spring.datasource.url=jdbc:postgresql://localhost:5432/challenge
spring.datasource.username=admin
spring.datasource.password=qwerty123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
#spring.main.lazy-initialization=true
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.tomcat.max-threads=10
server.tomcat.min-spare-threads=2

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none  
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

spring.jmx.enabled=false
spring.main.banner-mode=off
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.idle-timeout=45000
spring.datasource.hikari.leak-detection-threshold=2000

spring.jpa.generate-ddl=false
#logging.level.root=WARN

minio.root-user=admin
minio.root-password=qwerty123
minio.access-key=yKKfynctHkV6r4hB1Kry
minio.secret-key=dlbHGLk21mJRpeb49cnKIdqub8X7ZT0tz8PrP92E
minio.endpoint=${MINIO_URL:http://localhost:9000}

app.thread-pool.pool-size=10
app.thread-pool.max-pool-size=10
app.thread-pool.queue-capacity=20


